name: Cazar Canales Automáticamente
on:
  schedule:
    - cron: '0 8 * * *' # Se ejecuta todos los días a las 8 AM
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: {python-version: '3.10'}
      - name: Install dependencies
        run: |
          pip install requests PyGithub playwright
          playwright install chromium
      - name: Ejecutar cazador
        env:
          MI_TOKEN_GITHUB: ${{ secrets.MI_TOKEN_GITHUB }}
        run: python cazador_maestro.py
env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
